.TH "src/str Directory Reference" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_split\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strdup\&.c\fP"
.br
.ti -1c
.RI "file \fBft_striteri\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strjoin\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strlcat\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strlcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strlen\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strmapi\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strncmp\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strnstr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strrchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strtrim\&.c\fP"
.br
.ti -1c
.RI "file \fBft_substr\&.c\fP"
.br
.in -1c
