.TH "src/print Directory Reference" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_convert_base\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putchar_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putendl_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putnbr_base\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putnbr_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putpointer_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putstr_fd\&.c\fP"
.br
.in -1c
