.TH "src/char Directory Reference" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_isalnum\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isalpha\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isascii\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isdigit\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isprint\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isspace\&.c\fP"
.br
.ti -1c
.RI "file \fBft_tolower\&.c\fP"
.br
.ti -1c
.RI "file \fBft_toupper\&.c\fP"
.br
.in -1c
