.TH "src Directory Reference" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBchar\fP"
.br
.ti -1c
.RI "directory \fBlst\fP"
.br
.ti -1c
.RI "directory \fBmem\fP"
.br
.ti -1c
.RI "directory \fBprint\fP"
.br
.ti -1c
.RI "directory \fBsort\fP"
.br
.ti -1c
.RI "directory \fBstr\fP"
.br
.ti -1c
.RI "directory \fBswap\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_atoi\&.c\fP"
.br
.ti -1c
.RI "file \fBft_atoi_base\&.c\fP"
.br
.ti -1c
.RI "file \fBft_itoa\&.c\fP"
.br
.in -1c
