.TH "src/ft_atoi.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_atoi.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_atoi\fP (const char *nptr)"
.br
.RI "Convert string to int, and handle number\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_atoi (const char * nptr)"

.PP
Convert string to int, and handle number\&. 
.PP
\fBParameters\fP
.RS 4
\fInptr\fP string to convert 
.RE
.PP
\fBReturns\fP
.RS 4
int number 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBft_atoi\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
