.TH "src/mem/ft_bzero.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_bzero.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_bzero\fP (void *s, size_t n)"
.br
.RI "Set at 0, the n first bytes at the pointer adress\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_bzero (void * s, size_t n)"

.PP
Set at 0, the n first bytes at the pointer adress\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP pointer to the memory to set 
.br
\fIn\fP number of bytes to set at 0 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBft_bzero\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
