.TH "src/mem/ft_calloc.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_calloc.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_calloc\fP (size_t element_count, size_t element_size)"
.br
.RI "Allocates a new memory zone, and set all bits to zero\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * ft_calloc (size_t element_count, size_t element_size)"

.PP
Allocates a new memory zone, and set all bits to zero\&. 
.PP
\fBParameters\fP
.RS 4
\fIelement_count\fP number of elements 
.br
\fIelement_size\fP size of each element 
.RE
.PP
\fBReturns\fP
.RS 4
void* pointer to the new memory zone 
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBft_calloc\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
