.TH "src/char/ft_isprint.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char/ft_isprint.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_isprint\fP (int character)"
.br
.RI "Check if arg is in ascii table\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_isprint (int character)"

.PP
Check if arg is in ascii table\&. 
.PP
\fBParameters\fP
.RS 4
\fIcharacter\fP character to check 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 not in ascii table, anything else if in ascii table 
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBft_isprint\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
