.TH "src/lst/ft_lstiter_bonus.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lst/ft_lstiter_bonus.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_lstiter\fP (\fBt_list\fP *lst, void(*f)(void *))"
.br
.RI "Iterate on the linked list 'lst' and apply the function 'f' on the content of each element\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_lstiter (\fBt_list\fP * lst, void(* f )(void *))"

.PP
Iterate on the linked list 'lst' and apply the function 'f' on the content of each element\&. 
.PP
\fBParameters\fP
.RS 4
\fIlst\fP head of the linked list 
.br
\fIf\fP function to apply to the content of each element 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBft_lstiter_bonus\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
