.TH "src/lst/ft_lstsize_bonus.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lst/ft_lstsize_bonus.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_lstsize\fP (\fBt_list\fP *lst)"
.br
.RI "Count the number of elements in a list\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_lstsize (\fBt_list\fP * lst)"

.PP
Count the number of elements in a list\&. 
.PP
\fBParameters\fP
.RS 4
\fIlst\fP list to count 
.RE
.PP
\fBReturns\fP
.RS 4
int number of elements in the list 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBft_lstsize_bonus\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
