.TH "src/lst/ft_lstclear_bonus.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lst/ft_lstclear_bonus.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_lstclear\fP (\fBt_list\fP **lst, void(*del)(void *))"
.br
.RI "Deletes and free the memory of the element passed as a parameter, and all the elements that follow, using 'del' and free(3) Finally, the initial pointer must be set to NULL\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_lstclear (\fBt_list\fP ** lst, void(* del )(void *))"

.PP
Deletes and free the memory of the element passed as a parameter, and all the elements that follow, using 'del' and free(3) Finally, the initial pointer must be set to NULL\&. 
.PP
\fBParameters\fP
.RS 4
\fIlst\fP head of the linked list 
.br
\fIdel\fP function to apply to delete all the content of the element 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBft_lstclear_bonus\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
