.TH "src/mem/ft_memcpy.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_memcpy.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_memcpy\fP (void *destination, const void *source, size_t size)"
.br
.RI "Set a memory zone with a value, count times\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * ft_memcpy (void * destination, const void * source, size_t size)"

.PP
Set a memory zone with a value, count times\&. 
.PP
\fBParameters\fP
.RS 4
\fIdestination\fP memory zone to paste 
.br
\fIsource\fP memory zone to copy 
.br
\fIsize\fP number of times to set the value 
.RE
.PP
\fBReturns\fP
.RS 4
void* pointer to the memory zone 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBft_memcpy\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
