.TH "src/mem/ft_memset.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_memset.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_memset\fP (void *pointer, int value, size_t count)"
.br
.RI "Set a memory zone with a value, count times\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * ft_memset (void * pointer, int value, size_t count)"

.PP
Set a memory zone with a value, count times\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP memory zone to set 
.br
\fIvalue\fP value to set 
.br
\fIcount\fP number of times to set the value 
.RE
.PP
\fBReturns\fP
.RS 4
void* pointer to the memory zone 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBft_memset\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
