.TH "src/mem/ft_memmove.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_memmove.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_memmove\fP (void *destination, const void *source, size_t size)"
.br
.RI "Moves the memory blocks avoiding overlapping, until size blocks\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * ft_memmove (void * destination, const void * source, size_t size)"

.PP
Moves the memory blocks avoiding overlapping, until size blocks\&. 
.PP
\fBParameters\fP
.RS 4
\fIdestination\fP destination memory block 
.br
\fIsource\fP source memory block 
.br
\fIsize\fP size of the memory block 
.RE
.PP
\fBReturns\fP
.RS 4
void* pointer to the destination memory block 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBft_memmove\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
