.TH "src/mem/ft_memcmp.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_memcmp.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_memcmp\fP (const void *src, const void *set, size_t size)"
.br
.RI "Compares the first size bytes of the memory areas src and set\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_memcmp (const void * src, const void * set, size_t size)"

.PP
Compares the first size bytes of the memory areas src and set\&. 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP source memory block 
.br
\fIset\fP set memory block 
.br
\fIsize\fP size of the memory block 
.RE
.PP
\fBReturns\fP
.RS 4
int difference between the first different byte 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBft_memcmp\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
