.TH "src/print/ft_putnbr_base.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_putnbr_base.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBft_putnbr_base\fP (int nbr, char *base)"
.br
.RI "Putnbr with a particular base\&. "
.ti -1c
.RI "ssize_t \fBft_putnbr_bin\fP (int nbr)"
.br
.RI "Putnbr for binary\&. "
.ti -1c
.RI "ssize_t \fBft_putnbr_hex\fP (int nbr, char height)"
.br
.RI "Putnbr for hex or HEX\&. "
.ti -1c
.RI "ssize_t \fBft_putnbr_oct\fP (int nbr)"
.br
.RI "Putnbr for octal\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "ssize_t ft_putnbr_base (int nbr, char * base)"

.PP
Putnbr with a particular base\&. 
.PP
\fBParameters\fP
.RS 4
\fInbr\fP number to print 
.br
\fIbase\fP base to use 
.RE
.PP
\fBReturns\fP
.RS 4
ssize_t number of char printed 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBft_putnbr_base\&.c\fP\&.
.SS "ssize_t ft_putnbr_bin (int nbr)"

.PP
Putnbr for binary\&. 
.PP
\fBParameters\fP
.RS 4
\fInbr\fP number to print 
.RE
.PP

.PP
Definition at line \fB54\fP of file \fBft_putnbr_base\&.c\fP\&.
.SS "ssize_t ft_putnbr_hex (int nbr, char height)"

.PP
Putnbr for hex or HEX\&. 
.PP
\fBParameters\fP
.RS 4
\fInbr\fP number to print 
.br
\fIheight\fP 1 for hex, 0 for HEX 
.RE
.PP

.PP
Definition at line \fB75\fP of file \fBft_putnbr_base\&.c\fP\&.
.SS "ssize_t ft_putnbr_oct (int nbr)"

.PP
Putnbr for octal\&. 
.PP
\fBParameters\fP
.RS 4
\fInbr\fP number to print 
.RE
.PP

.PP
Definition at line \fB64\fP of file \fBft_putnbr_base\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
