.TH "src/print/ft_putchar_fd.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_putchar_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBft_putchar_fd\fP (char c, int fd)"
.br
.RI "Print the character 'c' on the file descriptor\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "ssize_t ft_putchar_fd (char c, int fd)"

.PP
Print the character 'c' on the file descriptor\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP character to print 
.br
\fIfd\fP file descriptor 
.RE
.PP
\fBReturns\fP
.RS 4
ssize_t number of char printed 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBft_putchar_fd\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
