.TH "src/print/ft_putpointer_fd.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_putpointer_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBft_putpointer_fd\fP (void *ptr)"
.br
.RI "Print pointer adress\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "ssize_t ft_putpointer_fd (void * ptr)"

.PP
Print pointer adress\&. 
.PP
\fBParameters\fP
.RS 4
\fIptr\fP pointer to print 
.RE
.PP
\fBReturns\fP
.RS 4
ssize_t number of char printed 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBft_putpointer_fd\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
