.TH "src/sort/ft_rev_int.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sort/ft_rev_int.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_rev_int\fP (int *tab, size_t size)"
.br
.RI "Reverse an array of ints\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_rev_int (int * tab, size_t size)"

.PP
Reverse an array of ints\&. 
.PP
\fBParameters\fP
.RS 4
\fItab\fP adress of the first element of the array 
.br
\fIsize\fP number of elements in the array 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBft_rev_int\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
