.TH "src/str/ft_substr.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_substr.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_substr\fP (char const *src, unsigned int start, size_t len)"
.br
.RI "Create a copy of source into a new pointer, at start, of size len NEEDS to be freed\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ft_substr (char const * src, unsigned int start, size_t len)"

.PP
Create a copy of source into a new pointer, at start, of size len NEEDS to be freed\&. 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP string to copy 
.br
\fIstart\fP start of the copy 
.br
\fIlen\fP size of the copy 
.RE
.PP
\fBReturns\fP
.RS 4
char* new string 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBft_substr\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
