.TH "src/str/ft_strchr.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strchr.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strchr\fP (const char *string, int searched_char)"
.br
.RI "Find first occurrence of searched_char\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ft_strchr (const char * string, int searched_char)"

.PP
Find first occurrence of searched_char\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP string to search in 
.br
\fIsearched_char\fP char to search 
.RE
.PP
\fBReturns\fP
.RS 4
char* index of Char found 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBft_strchr\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
