.TH "src/str/ft_strjoin.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strjoin.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strjoin\fP (char const *s1, char const *s2)"
.br
.RI "Allocates a new string, and returns the result of a concatenation of s1 and s2\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ft_strjoin (char const * s1, char const * s2)"

.PP
Allocates a new string, and returns the result of a concatenation of s1 and s2\&. 
.PP
\fBParameters\fP
.RS 4
\fIs1\fP string 1 
.br
\fIs2\fP string 2 
.RE
.PP
\fBReturns\fP
.RS 4
char* new string 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBft_strjoin\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
