.TH "src/str/ft_striteri.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_striteri.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_striteri\fP (char *s, void(*f)(unsigned int, char *))"
.br
.RI "Iterate the function f on string s\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_striteri (char * s, void(* f )(unsigned int, char *))"

.PP
Iterate the function f on string s\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP string to iterate 
.br
\fIf\fP function to apply 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBft_striteri\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
