.TH "src/str/ft_strlcat.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strlcat.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlcat\fP (char *dst, char *src, size_t size)"
.br
.RI "Concatenate src into dst, up to size bytes\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t ft_strlcat (char * dst, char * src, size_t size)"

.PP
Concatenate src into dst, up to size bytes\&. 
.PP
\fBParameters\fP
.RS 4
\fIdst\fP destination string 
.br
\fIsrc\fP source string 
.br
\fIsize\fP size of the destination string 
.RE
.PP
\fBReturns\fP
.RS 4
unsigned int size of the new string 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBft_strlcat\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
