.TH "src/str/ft_strlen.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strlen.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlen\fP (const char *the_string)"
.br
.RI "Len of string without '\\0'\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t ft_strlen (const char * the_string)"

.PP
Len of string without '\\0'\&. 
.PP
\fBParameters\fP
.RS 4
\fIthe_string\fP string to check 
.RE
.PP
\fBReturns\fP
.RS 4
size_t len of the string 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBft_strlen\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
