.TH "src/char/ft_tolower.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char/ft_tolower.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_tolower\fP (int character)"
.br
.RI "Transform majuscules into minuscules\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_tolower (int character)"

.PP
Transform majuscules into minuscules\&. 
.PP
\fBParameters\fP
.RS 4
\fIcharacter\fP character to check 
.RE
.PP
\fBReturns\fP
.RS 4
character in minuscules if was in majuscules OR character isn´t majuscules 
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBft_tolower\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
