.TH "src/char/ft_toupper.c" 3 "Mon Feb 17 2025 19:18:19" "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char/ft_toupper.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_toupper\fP (int character)"
.br
.RI "Transform minuscules into majuscules\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_toupper (int character)"

.PP
Transform minuscules into majuscules\&. 
.PP
\fBParameters\fP
.RS 4
\fIcharacter\fP character to check 
.RE
.PP
\fBReturns\fP
.RS 4
character in majuscule if was in minuscule OR character isn´t minuscule 
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBft_toupper\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
