.TH "Basics" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Basics \- Basic functions
.PP
 \- Basics functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_atoi\fP (const char *nptr)"
.br
.RI "Convert string to int, and handle number\&. "
.ti -1c
.RI "int \fBft_atoi_base\fP (char *str, char *base)"
.br
.RI "Atoi with a particular base\&. "
.ti -1c
.RI "char * \fBft_itoa\fP (int n)"
.br
.RI "Return a string representing the integer 'n' received as argument\&. "
.in -1c
.SH "Detailed Description"
.PP 
Basics functions\&. 


.SH "Function Documentation"
.PP 
.SS "int ft_atoi (const char * nptr)"

.PP
Convert string to int, and handle number\&. 
.PP
\fBParameters\fP
.RS 4
\fInptr\fP string to convert 
.RE
.PP
\fBReturns\fP
.RS 4
int number 
.RE
.PP

.SS "int ft_atoi_base (char * str, char * base)"

.PP
Atoi with a particular base\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP String to convert 
.br
\fIbase\fP Base to use for conversion 
.RE
.PP
\fBReturns\fP
.RS 4
int converted number 
.RE
.PP

.SS "char * ft_itoa (int n)"

.PP
Return a string representing the integer 'n' received as argument\&. 
.PP
\fBParameters\fP
.RS 4
\fIn\fP integer to convert 
.RE
.PP
\fBReturns\fP
.RS 4
char* string representing the integer 'n' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
