.TH "Free" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Free \- Free functions
.PP
 \- Free functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_frees\fP (void **ptr)"
.br
.RI "Frees multiple pointers\&. "
.in -1c
.SH "Detailed Description"
.PP 
Free functions\&. 


.SH "Function Documentation"
.PP 
.SS "void ft_frees (void ** ptr)"

.PP
Frees multiple pointers\&. 
.PP
\fBParameters\fP
.RS 4
\fIptr\fP Array of pointers 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
