.TH "src/ft_atoi.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_atoi.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_atoi\fP (const char *nptr)"
.br
.RI "Convert string to int, and handle number\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
