.TH "src/ft_atoi_base.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_atoi_base.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_atoi_base\fP (char *str, char *base)"
.br
.RI "Atoi with a particular base\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
