.TH "src/print/ft_convert_base.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_convert_base.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_check_base_atoi\fP (const char *base)"
.br
.RI "Check if base is valid for atoi_base\&. "
.ti -1c
.RI "size_t \fBft_check_base_putnbr\fP (const char *base)"
.br
.RI "Check if base is valid for putnbr_base\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
