.TH "src/ft_frees_va.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_frees_va.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdarg\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_frees_va\fP (void *ptr,\&.\&.\&.)"
.br
.RI "Frees multiple pointers using va_list\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_frees_va (void * ptr,  \&.\&.\&.)"

.PP
Frees multiple pointers using va_list\&. 
.PP
\fBParameters\fP
.RS 4
\fIptr\fP first pointer 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
