.TH "src/char/ft_isprint.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char/ft_isprint.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_isprint\fP (int character)"
.br
.RI "Check if arg is in ascii table and printable\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
