.TH "src/char/ft_isalpha.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char/ft_isalpha.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_isalpha\fP (int character)"
.br
.RI "Check if arg is a char alphabetic\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
