.TH "src/ft_itoa.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_itoa.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_itoa\fP (int n)"
.br
.RI "Return a string representing the integer 'n' received as argument\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
