.TH "src/char/ft_isspace.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char/ft_isspace.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_isspace\fP (int character)"
.br
.RI "Check if arg is a whitespace\&. "
.ti -1c
.RI "int \fBft_iswhitespace\fP (int character)"
.br
.RI "Alternative name for ft_isspace\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
