.TH "src/lst/ft_lstiter_bonus.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lst/ft_lstiter_bonus.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_lstiter\fP (\fBt_list\fP *lst, void(*f)(void *))"
.br
.RI "Iterate on the linked list 'lst' and apply the function 'f' on the content of each element\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
