.TH "src/lst/ft_lstadd_front_bonus.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lst/ft_lstadd_front_bonus.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_lstadd_front\fP (\fBt_list\fP **lst, \fBt_list\fP *new)"
.br
.RI "Adds the element ’new’ at the start of the list\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
