.TH "src/lst/ft_lstsize_bonus.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lst/ft_lstsize_bonus.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_lstsize\fP (\fBt_list\fP *lst)"
.br
.RI "Count the number of elements in a list\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
