.TH "src/lst/ft_lstdelone_bonus.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lst/ft_lstdelone_bonus.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_lstdelone\fP (\fBt_list\fP *lst, void(*del)(void *))"
.br
.RI "Free the memory of the element passed as a parameter using the function 'del' and free(3)\&. The memory of next must not be freed\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
