.TH "src/mem/ft_memchr.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_memchr.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const void * \fBft_memchr\fP (const void *memory_block, int searched_char, size_t size)"
.br
.RI "Research the first occurence of a value typed int, but interpreted as a char in a memory block\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
