.TH "src/mem/ft_memmove.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_memmove.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_memmove\fP (void *destination, const void *source, size_t size)"
.br
.RI "Moves the memory blocks avoiding overlapping, until size blocks\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
