.TH "src/mem/ft_memcmp.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem/ft_memcmp.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_memcmp\fP (const void *src, const void *set, size_t size)"
.br
.RI "Compares the first size bytes of the memory areas src and set\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
