.TH "src/print/ft_putnbr_base_hex.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_putnbr_base_hex.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBft_putnbr_hex_fd\fP (unsigned int nbr, char height, int fd)"
.br
.RI "Putnbr for hex or HEX\&. "
.ti -1c
.RI "ssize_t \fBft_putptr_fd\fP (unsigned long nbr, int fd)"
.br
.RI "Print pointer adress\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
