.TH "src/print/ft_putpointer_fd.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_putpointer_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBft_putpointer_fd\fP (const void *ptr)"
.br
.RI "Print pointer adress\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
