.TH "src/print/ft_putchar_fd.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_putchar_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBft_putchar_fd\fP (const char c, int fd)"
.br
.RI "Print the character 'c' on the file descriptor\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
