.TH "src/print/ft_putendl_fd.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_putendl_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBft_putendl_fd\fP (const char *s, int fd)"
.br
.RI "Print the string 's' on the file descriptor, followed by a newline\&. "
.ti -1c
.RI "ssize_t \fBft_putnendl_fd\fP (const char *s, size_t len, int fd)"
.br
.RI "Print the string 's' on the file descriptor, followed by a newline until a given size or the length of s if len is greater\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
