.TH "src/print/ft_putnbr_fd.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/print/ft_putnbr_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBft_putnbr_fd\fP (long long n, int fd)"
.br
.RI "Write the int 'n' on the given file descriptor\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
