.TH "src/sort/ft_rev_int.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sort/ft_rev_int.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_rev_int\fP (int *tab, size_t size)"
.br
.RI "Reverse an array of ints\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
