.TH "src/str/ft_strjoins_va.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strjoins_va.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdarg\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strjoins_va\fP (char const *str,\&.\&.\&.)"
.br
.RI "Allocates a new string, and returns the result of a concatenation of str and all the arguments last argument needs to be "\\0", NULL or ""\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * ft_strjoins_va (char const * str,  \&.\&.\&.)"

.PP
Allocates a new string, and returns the result of a concatenation of str and all the arguments last argument needs to be "\\0", NULL or ""\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string 1 
.br
\fI\&.\&.\&.\fP Variadic arguments 
.RE
.PP
\fBReturns\fP
.RS 4
char* new string 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
