.TH "src/lst/manipulation/ft_swap_nodes.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lst/manipulation/ft_swap_nodes.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_swap_nodes\fP (\fBt_list\fP **start, \fBt_list\fP *lst1, \fBt_list\fP *lst2)"
.br
.RI "Swap two nodes in a linked list (swap nodes, not content) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
