.TH "src/str/ft_strjoin.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strjoin.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strjoin\fP (char const *s1, char const *s2)"
.br
.RI "Allocates a new string, and returns the result of a concatenation of s1 and s2\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
