.TH "src/swap/ft_swap.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/swap/ft_swap.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_swap_int\fP (int *a, int *b)"
.br
.RI "Swap 2 int values\&. "
.ti -1c
.RI "void \fBft_swap_char\fP (char *a, char *b)"
.br
.RI "Swap 2 char values\&. "
.ti -1c
.RI "void \fBft_swap_str\fP (char **a, char **b)"
.br
.RI "Swap 2 string addresses\&. "
.ti -1c
.RI "void \fBft_swap_mem\fP (void **a, void **b)"
.br
.RI "Swap 2 memory adresses\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
