.TH "src/str/ft_strlcat.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strlcat.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlcat\fP (char *dst, const char *src, size_t size)"
.br
.RI "Concatenate src into dst, up to size bytes\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
