.TH "src/str/ft_strlcpy.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strlcpy.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlcpy\fP (char *dst, char *src, size_t size)"
.br
.RI "Copy of src into dst, up to size bytes\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t ft_strlcpy (char * dst, char * src, size_t size)"

.PP
Copy of src into dst, up to size bytes\&. 
.PP
\fBParameters\fP
.RS 4
\fIdst\fP destination string 
.br
\fIsrc\fP source string 
.br
\fIsize\fP size of the destination string 
.RE
.PP
\fBReturns\fP
.RS 4
size_t size of src 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
