.TH "src/str/ft_strlen.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/str/ft_strlen.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlen\fP (const char *the_string)"
.br
.RI "Len of string without '\\0'\&. "
.ti -1c
.RI "size_t \fBft_strlen_char\fP (const char *the_string, int character)"
.br
.RI "Number of occurrence of character in the string\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
