.TH "src/swap/ft_swap_no_temp.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/swap/ft_swap_no_temp.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_swap_char_no_temp\fP (char *a, char *b)"
.br
.RI "Works similarly as ft_swap_char but doens't use temporary variable SHOULD NOT BE USED IF a and b points at the same adress\&. "
.ti -1c
.RI "void \fBft_swap_int_no_temp\fP (int *a, int *b)"
.br
.RI "Works similarly as ft_swap_int but doens't use temporary variable SHOULD NOT BE USED IF a and b points at the same adress\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
