.TH "src/char/ft_tolower.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char/ft_tolower.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_tolower\fP (int character)"
.br
.RI "Transform majuscules into minuscules\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
