.TH "src/char/ft_toupper.c" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/char/ft_toupper.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_toupper\fP (int character)"
.br
.RI "Transform minuscules into majuscules\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
