.TH "s_list" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_list \- Structure for linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <libft\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBcontent\fP"
.br
.ti -1c
.RI "struct \fBs_list\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for linked list\&. 
.SH "Field Documentation"
.PP 
.SS "void* s_list::content"
Pointer to the data stored in the node 
.SS "struct \fBs_list\fP* s_list::next"
Pointer to the next node in the list 

.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
