.TH "SORT" 3 "Libft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SORT \- Sorting arrays
.PP
 \- Sorting arrays\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_rev_int\fP (int *tab, size_t size)"
.br
.RI "Reverse an array of ints\&. "
.in -1c
.SH "Detailed Description"
.PP 
Sorting arrays\&. 


.SH "Function Documentation"
.PP 
.SS "void ft_rev_int (int * tab, size_t size)"

.PP
Reverse an array of ints\&. 
.PP
\fBParameters\fP
.RS 4
\fItab\fP adress of the first element of the array 
.br
\fIsize\fP number of elements in the array 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Libft from the source code\&.
